-- phpMyAdmin SQL Dump
-- version 4.9.11
-- https://www.phpmyadmin.net/
--
-- Host: localhost:3306
-- Generation Time: Apr 21, 2023 at 08:11 AM
-- Server version: 10.5.19-MariaDB
-- PHP Version: 7.4.33

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `publishe_webpresentation`
--

-- --------------------------------------------------------

--
-- Table structure for table `present`
--

CREATE TABLE `present` (
  `id` int(11) NOT NULL,
  `ad_format` varchar(255) NOT NULL,
  `template` varchar(255) NOT NULL,
  `category` varchar(255) NOT NULL,
  `average_ctr` varchar(255) NOT NULL,
  `dimensions` varchar(255) NOT NULL,
  `duration` varchar(255) NOT NULL,
  `functionality` varchar(255) NOT NULL,
  `reviews` longtext NOT NULL,
  `description` longtext NOT NULL,
  `demo_link` varchar(255) NOT NULL,
  `meta_keywords` longtext NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=latin1 COLLATE=latin1_swedish_ci;

--
-- Dumping data for table `present`
--

INSERT INTO `present` (`id`, `ad_format`, `template`, `category`, `average_ctr`, `dimensions`, `duration`, `functionality`, `reviews`, `description`, `demo_link`, `meta_keywords`) VALUES
(1, 'Video', 'In Banner Video Creative', 'Banking', '1.00%', '300x600, 320x480, 480x320, 970x250', '10 min', 'Auto', 'no data', 'Help HC with the master look of your Creative with the applicable video and your Programmatic creatives will be ready within hours!\n\nRequirements:\nOpen Files in .psd or .ai format\nVideo under 30s\n\n', 'https://ad.hockeycurve.com/ad.php?zoneid=300x600&client=razorpay&fcat=gate1', 'Standard - Banking, video, branding, Combination creative, BFSI, rich media,Video + Rich Media, Performance,\nCreative - 2 copies, 1 CTA,\nTechnical - 1LP, Single LP, \nAnimation - Popup cta animation,\nBrand - Razorpay'),
(2, 'Display', 'Rich Media Creative + Flip based carousel Combo', 'Banking', '', '300x250, 300x600, 320x480, 480x320, 970x250', '10 min', 'Auto + Manual', '', '\nShowcase n number of services, products and USPs with this dynamic and interactive format!\n\nHere, the creative not only introduces the credit card with animation but also emphasizes on the USPs.\n\n#Just flip it!\n\nRequirements:\nOpen Files in .psd or .ai format\nOrder of cards', 'https://ad.hockeycurve.com/ad.php?zoneid=300x250&client=idfc&fcat=flipidfc', 'Standard - Banking, performance, Offers, USPs, BFSI\nCreative - 5 USPs, 1 CTA, 2 copies,\nTechnical - 1 LP, Single LP, \nAnimation - Flip, transition,Float animation, Fade out animation, \nBrand - IDFC'),
(3, 'Display', 'Swipe Creative - Non Feed', 'Banking', '0.73%', '300x250, 300x600, 320x480, 480x320', '12 min', 'Auto + Manual', '', 'Regular carousels getting monotonous?\nSwitch it up with HC Swipe! This enables user and auto swiping through the deck of cards\n\nThe creative is displaying the relevant offers on their home brands!\n\nRequirements:\nOpen Files in .psd or .ai format\nList of products/ feed\n', 'https://ad.hockeycurve.com/ad.php?zoneid=300x600&client=idfc&fcat=swipeidfc', 'Standard -Banking, swipe, Offers, features, User Initiated Swipe, BFSI\nCreative - 5 USPs, 1 CTA, 2 copies,\nTechnical - 1 LP, Single LP, \nAnimation - Swipe,Nudge,  \nBrand - IDFC'),
(4, 'Display', 'Dynamic City + Auto Carousel', 'Banking', '1.89%', '300x250, 300x600, 320x480, 480x320', '12 min', 'Auto', '', 'Grab attention instantly!\n\nThe auto carousel format helps you showcase n number of products in loop keeping you user engaged and hungry for more!\n\nAll the various USPs have been highlighted to persuade the user to Open their accounts instantly!\n\nRequirements:\nOpen Files in .psd or .ai format\nProduct Images\n', 'https://ad.hockeycurve.com/ad.php?zoneid=special&client=idfc&fcat=cam2spl&staging=only', 'Standard - Banking, carousel, auto, dynamic city, USPs, Geo Location,API, BFSI, Performance, account, savings\nCreative - 4 USPs, 1 CTA, 1 copy,Bottom Navigation\nTechnical - 1 LP, Single LP, \nAnimation - Shimmer, Auto carousel, Auto transition  \nBrand - IDFC'),
(5, 'Display', 'Flip Carousel - Non feed', 'Banking', '1.89%', '300x250, 300x600, 320x480, 480x320', '11 min', 'Auto + Manual', '', '\nShowcase n number of services, products and USPs with this dynamic and interactive format!\n\nAll the various USPs have been highlighted to persuade the user to Open their accounts instantly!\r\n\n\n#Just flip it!\n\nRequirements:\nOpen Files in .psd or .ai format\nOrder of cards', 'https://ad.hockeycurve.com/ad.php?zoneid=300x600&client=idfc&fcat=rr77x2', 'Standard - Banking, performance,USPs, Flip, BFSI, Credit Card\nCreative - 7 USPs, 1 CTA, 2 copies, \nTechnical - 1 LP, Single LP, \nAnimation - Flip,  Fade in down, flash\nBrand - IDFC'),
(6, 'Display', 'EMI calculator1 - Single frame', 'Banking', '0.86%', '300x250, 300x600, 320x480, 480x320', '15 min', 'Manual', '', 'Instant Gratification!\n\nThis personal loan calculator helps calulate EMI amount instantly even before you reach the landing page. \n\nThis exercise builds trust, increases engagement and helps reduce bounce rate.\n\nRequirements:\nOpen Files in .psd or .ai format\n', 'http://ad.hockeycurve.com/ad.php?client=abfl&zoneid=336x280&fcat=calculator', 'Standard - Banking, Calculator, EMI, Loan, Interest, Personal Loan, interactive, performance, auto calculate,  dynamic copy\nCreative - Dropdown, radio buttons,  \nTechnical - 1 LP, Single LP, \nAnimation - \nBrand - Aditya Birla'),
(7, 'Display', 'EMI calculator2 - Multi Frame', 'Banking', '', '300x250, 300x600, 320x480, 480x320', '12 min', 'Manual', '', 'Instant Gratification!\n\nThis is what explains this format.  Input a few details to instantly calculate your investment even before you reach the landing page. \n\nDisplay multiple KVs in 1 ad itself while making each frame interactive !\n\nRequirements:\nOpen Files in .psd or .ai format\n', 'https://ad.hockeycurve.com/ad.php?zoneid=300x250&client=abfl&fcat=newcalculator', 'Standard - Banking, Carousel, Calculator, EMI, Loan, Interest, Personal Loan, intercative, Performance, dynamic copy\nCreative - Dropdown, radio buttons, Arrow navigation, Arrow Buttons\nTechnical - 1 LP, Single LP, \nAnimation - Auto roatet, auto carousel, right to left\nBrand - Aditya Birla'),
(8, 'Display', 'EMI calculator3 - Single frame with Set Amount', 'Banking', '', '300x250, 300x600, 320x480, 480x320', '12 min', 'Manual', '', 'Find out what your EMI will be for a set amount!\n\nInput a few details to instantly calculate your investment even before you reach the landing page. \n\nThis calculator will help calculate your Monthly EMI for any selected tenure.\nRequirements:\nOpen Files in .psd or .ai format\n', 'https://ad.hockeycurve.com/ad.php?zoneid=300x250&client=abfl&fcat=calculator1&staging=only', 'Standard - Banking, Personal Loan, Interrest, Loan, EMI, Loan, Interest, Tenure, Interest, Performance,BFSI, dynamic copy\nCreative - Dropdown, radio buttons, Arrow navigation, Arrow Buttons\nTechnical - 1 LP, Single LP, \nAnimation - Auto rotate, auto carousel, right to left\nBrand - Aditya Birla'),
(9, 'Display', 'Montly Interest Calculator - Multi Frame', 'Banking', '', '300x250, 300x600, 320x480, 480x320', '14 min', 'Manual', '', 'Instant Gratification!\n\nThis is what explains this format.  Input a few details to instantly calculate your investment even before you reach the landing page. \n\nCalculate monthly interest with just 1 input! How easy is that?\n\nRequirements:\nOpen Files in .psd or .ai format\n', 'https://ad.hockeycurve.com/ad.php?zoneid=300x250&client=idfc&fcat=calc&staging=only', 'Standard - Banking, Savings, Calculator, Interest, Account Balance, Monthly Interest, BFSI, Performance, Savings, Fixed Interest, dynamic copy\nCreative - Input text, text field, 2 frames, 2 copies, 2 CTA bittons\nTechnical - 1 LP, Single LP, \nAnimation - Shimmer, fade , transition\nBrand - IDFC'),
(10, 'Display', 'Cube Carousel - Non Feed', 'Banking', '0.93%', '300x250, 300x600, 320x480, 480x320', '12 min', 'Auto', '', 'This is one of the newest formats launches at HC!\nIt\'s an attention grabber with its animation and allows us to showcase 6 features in an innovative format to the user!\n\nRequirements:\nOpen Files in .psd or .ai format\nHigh Resolution Images of the product\n', 'https://ad.hockeycurve.com/ad.php?zoneid=300x600&client=idfc&fcat=gi0sqq', 'Standard - Banking, Cube, USPs, Credit Card, BFSI, Performance, auto carousel\nCreative - 2 copies,1 cta\nTechnical - 1 LP, Single LP, \nAnimation - Auto carousel,  popup \nBrand - IDFC'),
(11, 'Display', 'Swipe Carousel - Non feed', 'Banking', '0.73%', '300x250, 300x600, 320x480, 480x320', '11 min', 'Auto + Manual', '', '\nRegular carousels getting monotonous?\nSwitch it up with HC Swipe! This enables user and auto swiping through the deck of cards.\n\nThe cards focus on the key features of the product and let the user know to sign up instantly\n\nRequirements:\nOpen Files in .psd or .ai format\nList of products/ feed\n', 'https://ad.hockeycurve.com/ad.php?zoneid=300x600&client=idfc&fcat=ycicn', 'Standard -Banking, Swipe, USPs, Credit Card, performance, auto carousel\nCreative - 2 copies,1 cta\nTechnical - 1 LP, Single LP, \nAnimation - Zoom, auto swipe, fade in bottom to up\nBrand - IDFC'),
(12, 'Display', 'Rich Media creative with animation', 'Banking', '1.89%', '300x250, 300x600, 320x480, 480x320', '8 min', 'Auto', '', 'Static creatives are old school.\n\nSwitch to animated creatives and showcase eye catchy creatives with much ease.\n\nRequirements:\nOpen Files in .psd or .ai format\n', 'https://ad.hockeycurve.com/ad.php?zoneid=300x250&client=hdfc&fcat=swiss', 'Standard -Banking, Personal Loan, branding, performance, BFSI\nCreative - 1 copy,1 cta, \nTechnical - 1 LP, Single LP, \nAnimation - Motion bg, left, right, fade in\nBrand - HDFC'),
(13, 'Display', 'Savings Calculator - Multi Frame - Slider+ Dropdown', 'Banking', '', '300x250, 300x600, 320x480, 480x320', '15 min', 'Manual', '', 'Instant Gratification!\n\nThis is what explains this format.  Input a few details to instantly calculate your investment even before you reach the landing page. \n\nInteractivity is added by a combination of slider and a dropdown to make it super engaging and fun to use!\n\nRequirements:\nOpen Files in .psd or .ai format\n', 'https://ad.hockeycurve.com/ad.php?zoneid=300x600&client=idfc&fcat=calculator', 'Standard -Banking, Savings, interest, Earnings, Calculate, Open account, account , performance, BFSI, auto calculate, dynamic copy\nCreative - 3 copies, 2 ctas\nTechnical - 1 LP, Single LP, \nAnimation - Fade in up, pop up, \nBrand - IDFC'),
(14, 'Display', 'Savings Calculator -Multi Frame - Slider', 'Banking', '', '300x250, 300x600, 320x480, 480x320', '18 min', 'Manual', '', 'Instant Gratification!\n\nThis is what explains this format.  Input a few details to instantly calculate your investment even before you reach the landing page. \n\nInteractivity with the sliders in the ad will definitely increase your engagement and make the experience memorable for the user.\n\nRequirements:\nOpen Files in .psd or .ai format\n', 'https://ad.hockeycurve.com/ad.php?zoneid=300x600&client=idfc&fcat=intercalc', 'Standard -Banking, savings, slider, calculator, interest, Performance, interactive, BFSI, auto calculate, Dynamic copy\nCreative - 3 copies, 2 ctas\nTechnical - 1 LP, Single LP, \nAnimation - Zoom out, pop up, \nBrand - IDFC'),
(15, 'Display', 'Returns Calculator', 'Insurance', '', '300x250, 300x600, 320x480, 480x320', '12 min', 'Manual', '', 'Instant Gratification!\r\n\r\nThis is what explains this format.  Input a few details to instantly calculate your investment even before you reach the landing page. \r\n\r\nThis exercise builds trust, increases engagement and helps reduce bounce rate.\r\n\r\nRequirements:\r\nOpen Files in .psd or .ai format\r', 'https://ad.hockeycurve.com/ad.php?zoneid=300x250&client=franklin&fcat=frankdc6', 'Standard -Insurance, Dropdown, Debt Fund, Annual returns,  Performance, BFSI, interactive\nCreative - 1 copy, 1 cta\nTechnical - 1 LP, Single LP, \nAnimation - Top, shimmer \nBrand - Franklin templeton'),
(16, 'Display', 'Investment Calculator', 'Insurance', '', '300x250, 300x600, 320x480, 480x320', '12 min', 'Manual', '', 'A child\'s dream is of utmost importance to his family. \n\nTo ensure you have saved enough to help him fin dout your goal amount instantly!\n\nRequirements:\nOpen Files in .psd or .ai format\n', 'https://ad.hockeycurve.com/ad.php?zoneid=300x250&client=franklin&fcat=frankdc2', 'Standard -Insurance, calculator, Child\'s education plan, Invest, Future Value,  Performance,Auto calculate, \nCreative - 2 copies, 2 ctas\nTechnical - 1 LP, Single LP, \nAnimation - No animation\nBrand - Franklin templeton'),
(17, 'Display', 'Rich Media with animation +\n(Geo)', 'Insurance', '', '300x250, 300x600, 320x480, 480x320', '9 min', 'Auto', '', 'Static creatives are old school.\n\nSwitch to animated creatives and showcase eye catchy creatives with much ease\n\nAuto Geo detection helps create a personalized touch..\n\nRequirements:\nOpen Files in .psd or .ai format\n', 'https://ad.hockeycurve.com/ad.php?zoneid=300x250&client=bajajcity&fcat=bajal1dc', 'Standard -Insurance,Rich Media, Geo Location, Dynamic Elements, Performance, Branding\nCreative - 2 copies, 1 Cta\nTechnical - 1 LP, Single LP, \nAnimation - Zoom, flash and left\nBrand - Bajaj Allianz'),
(18, 'Display', 'Rich Media with Animation -\n(Dynamic date and time)', 'Insurance', '', '300x250, 300x600, 320x480, 480x320', '10 min', 'Auto', '', 'Static creatives are old school.\n\nSwitch to animated creatives and showcase eye catchy creatives with much ease.\n\nDynamic Date and Time detection helps create a personalized touch..\r\n\n\nRequirements:\nOpen Files in .psd or .ai format\n', 'https://ad.hockeycurve.com/ad.php?zoneid=300x250&client=bajajtimer&fcat=bajal4dc', 'Generic -Insurance, Animaton, Rich Media, Dynamic Date, Dynamic Time,  Performance, API, BFSI\nCreative - 2 copies, 1 Cta\nTechnical - 1 LP, Single LP, \nAnimation - Top, Bounce\nBrand - Bajaj Allianz'),
(19, 'Display', 'Auto Carousel', 'Insurance', '1.89%', '300x250, 300x600, 320x480, 480x320', '10 min', 'Auto', '', 'Grab attention instantly!\n\nThe auto carousel format helps you showcase n number of products in loop keeping you user engaged and hungry for more!\n\nHere, the USPs are displayed one after the other to keep the users engaged and hungry for more information.\n\nRequirements:\nOpen Files in .psd or .ai format\nProduct Images\n', 'https://ad.hockeycurve.com/ad.php?zoneid=300x250&client=bajajcarous&fcat=bpvdcfive\r\n\r\n', 'Generic -Insurance,Auto Carousel, USPs,  Performance, BFSI\nCreative - 2 copies, 1 Cta\nTechnical - 1 LP, Single LP, \nAnimation - Fade in down, Bounce\nBrand - Bajaj Allianz'),
(20, 'Display', 'USP swipe with gesture', 'Insurance', '0.73%', '300x250, 300x600, 320x480, 480x320', '9 min', 'Auto + Manual', '', '\nHighlighting the USPs of your service is essential for brand awareness and conversion.\nMake your USPs the Hero of your creative. This unique interactive format peeks curiosity and keeps the user engaged.\n\nThe Gesture creates a UX for the user and prompts them to engage with the ad\n\nRequirements:\nOpen Files in .psd or .ai format\n', 'https://ad.hockeycurve.com/ad.php?zoneid=300x250&client=bajajswipe&fcat=bajspi6dc', 'Generic  - Insurance,Auto Swipe, Manual Swipe, Gesture, USPs, Features,  Performance, BFSI\nCreative - 2 copies, 1 Cta\nTechnical - 1 LP, Single LP, \nAnimation - Auto Swipe, Shake, right, zoom in and out, back in down\nBrand - Bajaj Allianz'),
(21, 'Display', 'USP Swipe', 'Insurance', '0.76%', '300x250, 300x600, 320x480, 480x320', '12 min', 'Auto + Manual', '', '\nHighlighting the USPs of your service is essential for brand awareness and conversion.\n\nMake your USPs the Hero of your creative. This unique interactive format peeks curiosity and keeps the user engaged.\n\nRequirements:\nOpen Files in .psd or .ai format\n', 'https://ad.hockeycurve.com/ad.php?zoneid=300x250&client=bajajswipe&fcat=baajs', 'Generic  - Insurance, Swipe, USPs, Features,  Performance, BFSI\nCreative - 2 copies, 1 Cta\nTechnical - 1 LP, Single LP, \nAnimation - Auto Swipe, right, flip\nBrand - Bajaj Allianz'),
(22, 'Display', 'Premium Calculator', 'Insurance', '', '300x250, 300x600, 320x480, 480x320', '12 min', 'Auto', '', 'Calculators and applying for insurance is no more as difficult!\n\nThis ad format simplifies it both! Input a few details to instantly calculate your premium instantly!\n\nRequirements:\nOpen Files in .psd or .ai format\n', 'https://ad.hockeycurve.com/ad.php?zoneid=300x600&client=bajisd&fcat=dc9', 'Generic  - Insurance, Calculator, Premium, Quote, Health Insurance,  Performance, Insurance, BFSI, dropdown, Quote, Dynamic copy\nCreative - 2 copies, 1 Cta, dropdowns, selection buttons\nTechnical - 1 LP, Single LP, \nAnimation - Flip, heartbeat\nBrand - Bajaj Allianz'),
(23, 'Display', 'Click to call', 'Insurance', '', '300x250, 300x600, 320x480, 480x320', '8 min', 'Auto', '', 'Make a call as soon as you see an offer you would like to avail or know more about.\n\nThis unique feature integrates a functionality such that post click the number will get auto pasted in your mobile device ready to make the call\n\nRequirements:\nOpen Files\nContact Information', 'https://ad.hockeycurve.com/ad.php?zoneid=300x250&client=bajaj&fcat=bjdc10', 'Generic  - Health Insurance, Click to call, Performance, Interaction, BFSI\nCreative - 1 copy, 1 Cta\nTechnical - 1 LP, Single LP, \nAnimation - Back in down, pulse\nBrand - Bajaj Allianz\n'),
(24, 'Display', 'Rich media with animation', 'Insurance', '', '300x250, 300x600, 320x480, 480x320', '8 min', 'Auto', '', 'Brownie points!\n\nWho doesn\'t want them? Apply for health insurance and seek all the perks alongside!\n\n\nRequirements:\nOpen Files in .psd or .ai format\nVideo under 30s\n\n', 'https://ad.hockeycurve.com/ad.php?zoneid=300x250&client=futurauto&fcat=fdc1js', 'Generic  - Health Insurance, Auto Carousel, USPs, Features, benefits, Performance, Branding, BFSI\nCreative - 2 copies, 1 Cta\nTechnical - 1 LP, Single LP, \nAnimation - Left, bounce\nBrand - Future Generali\n'),
(25, 'Display', 'Horizontal card flip', 'Insurance', '0.66%', '300x250, 300x600, 320x480, 480x320', '8 min', 'Auto + Manual', '', '\nShowcase n number of services, products and USPs with this dynamic and interactive format!\n\n#Just flip it!\n\nRequirements:\nOpen Files in .psd or .ai format\nOrder of cards', 'https://ad.hockeycurve.com/ad.php?zoneid=300x250&client=futureflip&fcat=fli4dc', 'Generic  -Health Insurance, Auto Carousel, USPs, Features, benefits, Flip, Performance, BFSI\nCreative - 1 Cta, Horizontal card\nTechnical - 1 LP, Single LP, \nAnimation -Flip\nBrand - Future Generali'),
(26, 'Display', '360 Carousel', 'Insurance', '1.20%', '300x250, 300x600, 320x480, 480x320', '10 min', 'Auto', '', 'Talk about innovation and you have it!\n\nThis ad format allows a unique experience to showcase your USPs. The cards moving in the ad are eye catchy and grab the user\'s attention instantly!\n\nRequirements:\nOpen Files in .psd or .ai format\n', 'https://ad.hockeycurve.com/ad.php?zoneid=300x250&client=futgen&fcat=dc6', 'Generic - Health Insurance, Auto Carousel, USPs, Features, benefits,  Performance, BFSI\nCreative - 1 Cta, 2 copies\nTechnical - 1 LP, Single LP\nAnimation -Rotate, Fade in, Flash\nBrand - Future Generali'),
(27, 'Display', 'Card Flip', 'Insurance', '1.89%', '300x250, 300x600, 320x480, 480x320', '8 min', 'Auto + Manual', '', '\nShowcase n number of services, products and USPs with this dynamic and interactive format!\n\n#Just flip it!\n\nRequirements:\nOpen Files in .psd or .ai format\nOrder of cards', 'https://ad.hockeycurve.com/ad.php?zoneid=300x600&client=tataaia&fcat=taiflip', 'Generic - Health Insurance, Auto Carousel, Performance, Plans, Policies, terms, age,  assured sum, flip, BFSI, Interactive\nCreative - 1 Cta, 1 copy\nTechnical - 1 LP, Single LP\nAnimation - Fade in up, Flip\nBrand - Future Generali'),
(28, 'Display', 'Canvas Swipe', 'Insurance', '', '300x250, 300x600, 320x480, 480x320', '8 min', 'Auto + Manual', '', 'Want to run multiple campaigns with budget only for one?\nThis template allows you to showcase multiple creatives which can be auto and user initiated.\n\nYou can now not just swipe the cards but all the entire ad!\n\nRequirements:\nOpen Files in .psd or .ai format\nOrder of the creatives\n', 'https://ad.hockeycurve.com/ad.php?zoneid=300x250&client=tataaia&fcat=taiimgsl', 'Generic - Health Insurance, Swipe, Term plans, Insurance,  Performance, BFSI, Intercative\nCreative - 4 Ctas, 8 copies\nTechnical - 1 LP, Single LP\nAnimation - Fade in up, Flip\nBrand - Future Generali'),
(29, 'Display', 'Interactive Vertical Slider', 'Insurance', '', '300x250, 300x600, 320x480, 480x320', '8 min', 'Manual', '', 'How do I make my users understand the problem my brand is solving?\n\nThis ad format is for you. It can be used as an question - answer, problem - solution and comparative format.\n\nRequirements:\nOpen Files in .psd or .ai format\n', 'https://ad.hockeycurve.com/ad.php?zoneid=300x250&client=tataaia&fcat=taislidi', 'Generic - Health Insurance, Term Plans, Performance, BFSI, Interactive\nCreative - 2 Ctas, 2 copies\nTechnical - 1 LP, Single LP\nBrand - TATA AIA'),
(30, 'Display', 'Dropdown Based', 'Insurance', '2.21%', '300x250, 300x600, 320x480, 480x320', '12 min', 'Manual', '', 'Let the user choose!\n\nSpecific information based on user selection serves as a catalyst to conversion through instant gratification.\n\nSelect the exact plan you want to know about to get the relevant information\n\nRequirements:\nOpen Files in .psd or .ai format\n', 'https://ad.hockeycurve.com/ad.php?zoneid=300x250&client=tataaia&fcat=taidropdn', 'Generic - Health Insurance, Swipe, Term plans, Saving Plans, Retirement plans, Performance, Interactive, BFSI\nCreative - 2 Copies, 1 CTA\nTechnical - 1 LP, Single LP\nBrand - TATA AIA'),
(31, 'Display', 'Rich Media Creative with Animation', 'Financial Services - Sensex', '', '300x250, 300x600, 320x480, 480x320', '10 min', 'Auto', '', 'Show real time sensex data at any specific point in time with this format! Pair it up with a dynamic communication at various touchpoints and customise it however you like.\n\nRequirements:\nOpen Files in .psd or .ai format\nTouchpoints  and Dynamic copies\n', 'https://ad.hockeycurve.com/ad.php?zoneid=300x250&client=franklin&fcat=frankdc4', 'Generic - Sensex, Nifty, points, charts, Dynamic Time, Dynamic date, Dynamic Copies,  API, Performance, API, BFSI\nCreative - 2 copies, 1 cta\nTechnical - 1 LP, Single LP\nAnimation -Fade in up\nBrand - Franklin Templeton'),
(32, 'Display', 'Rich Media Creative with Animation', 'Financial Services - Sensex', 'Pending', '300x250, 300x600, 320x480, 480x320', '12 min', 'Auto', '', 'This interesting format allows you to display the sensex points over a period of 1 day!\n\nThe concantination of real time data with dynamic date helps add a layer of personalization and communication for the users. \n\nRequirements:\nOpen Files in .psd or .ai format\nTouchpoints  and Dynamic copies\n', 'https://ad.hockeycurve.com/ad.php?zoneid=300x250&client=livemint&fcat=sens', 'Generic - Sensex, Nifty, points, charts, Dynamic date, API,Performance, BFSI\nCreative - 3 copies, 1 cta\nTechnical - 1 LP, Single LP\nAnimation -Fade in up, Shimmer\nBrand - Livemint\n'),
(33, 'Display', 'Rich Media Creative with Animation', 'Financial Services - Stocks', 'Pending', '300x250, 300x600, 320x480, 480x320', '12 min', 'Auto', '', 'Description:\nShowcase what the audience wants.\n\nThis ad format displays the sensex points when they have increased. In the case where sensex drops, real time prices for stocks are displayed.\n\nRequirements:\nOpen Files in .psd or .ai format\nKey stocks - Names logos\n\n', 'https://ad.hockeycurve.com/ad.php?zoneid=300x250&client=groww&fcat=growdc2', 'Generic - Stocks, stock name, stock price, dynamic time, dynamic date, API, Performance\nCreative - 1 copy, 1 cta\nTechnical - 1 LP, Single LP\nAnimation -Right, zoom in and out\nBrand - Groww\n'),
(34, 'Display', 'Rich Media Creative with Animation', 'Financial Services - Sensex', 'Pending', '300x250, 300x600, 320x480, 480x320', '10 min', 'Auto', '', 'Show real time sensex data with this format! Pair it up with a dynamic communication at various touchpoints and customise it the way you like!\n\nHere, when sensex is high , real time data is displayed. When sensex falls, default communication is displayed.\n\nRequirements:\nOpen Files in .psd or .ai format\nTouchpoints  and Dynamic copies\n', 'https://ad.hockeycurve.com/ad.php?zoneid=300x600&client=angelbroking&fcat=promo', 'Generic -Sensex, Nifty, points, charts, Dynamic Copies,  API, Performance, BFSI\nCreative - 1 copy, 1 cta\nTechnical - 1 LP, Single LP\nAnimation -Fade in up, zoom in and out\nBrand - Angel Broking'),
(35, 'Display', 'Rich Media Creative with Animation', 'Financial Services - Stocks', 'Pending', '300x250, 300x600, 320x480, 480x320', '10 min', 'Auto', '', 'Description:\n\nThis format displays the top sensex losers in real time. It displays real time information in terms of stock prices, % Drop in prices relevant to the dynamic date.\n\nRequirements:\nOpen Files in .psd or .ai format\nKey stocks\n', 'https://ad.hockeycurve.com/ad.php?zoneid=300x250&client=growauto&fcat=dcfive', 'Generic - Sensex,  Stocks, stock name, stock price, dynamic date, API, Performance, BFSI\nCreative - 1 copy, 1 cta\nTechnical - 1 LP, Single LP\nAnimation -Fade in up, zoom in and out, right\nBrand - Groww'),
(36, 'Display', 'Rich Media Creative with Animation', 'Financial Services', 'Pending', '300x250, 300x600, 320x480, 480x320', '8 min', 'Auto', '', 'Help HC with the master look of your creative and your HD programmatic creatives will be ready within hours!\n\nIt\'s a combination of a performance and branding creative that prompts the user to star their investment journey.\n\nRequirements:\nOpen Files in .psd or .ai format\n', 'https://ad.hockeycurve.com/ad.php?zoneid=300x250&client=growauto&fcat=gro14js', 'Generic - Animation, Performance, Branding, BFSI, \nCreative - 1 copy, 1 cta\nTechnical - 1 LP, Single LP, Playstore, App store \nAnimation -Fade in right, zoom in and out\nBrand - Groww\n'),
(37, 'Display', 'Auto Swipe Carousel', 'Financial Services', 'Pending', '300x250, 300x600, 320x480, 480x320', '12 min', 'Auto', '', 'You see a billion ads for various companies on the daily. Relate and understand them by knowing their key offerings!\n\nThis format does just that, it showcases all offerings in an innovative manner to grab the user\'s attention!\n\nRequirements:\nOpen Files in .psd or .ai format\nOfferings\n', 'https://ad.hockeycurve.com/ad.php?zoneid=300x250&client=growswipe&fcat=growws', 'Generic -Swipe, Services, Performance, Interactive, BFSI\nCreative - 1 copy, 1 cta\nTechnical - 1 LP, Single LP, Playstore, App store \nAnimation -Zoom out, auto swipe\nBrand - Groww'),
(38, 'Display', 'Crypto - Dynamic Bitcoin', 'Financial Services - Crypto', 'Pending', '300x250, 300x600, 320x480, 480x320', '18 min', 'Auto', '', 'Show the most precise and relevant data to your users in a view!\r\n\r\nAPI integrated mechanism allows all the data to change dynamically at the backend\r\n\r\nRequirements:\r\nOpen Files in .psd or .ai format\r\n', 'https://ad.hockeycurve.com/ad.php?zoneid=300x600&client=wazirx&fcat=crypto', 'Generic - Pair name, Volume, change, API, Crypto, Bitcoin, Trading, API, Performance, BFSI\nCreative - 1 copy, 1 cta\nTechnical - 1 LP, Single LP\nAnimation -Shimmer\nBrand - Wazirx'),
(39, 'Display', 'Copy change on every refresh', 'Financial Services - Sensex', 'Pending', '300x250, 300x600, 320x480, 480x320', '18 min', 'Auto', '', 'This exciting template changes copies and key visuals based on the predefined triggered without showcasing any specific data!\r\nNot just that, it also showcases different creatives on every refresh!\r\n\r\nRequirements:\r\nOpen Files in .psd or .ai format\r\nTouchpoints  and Dynamic copies\r\n', 'https://ad.hockeycurve.com/ad.php?zoneid=300x250&client=franklin&fcat=franklintemp4', 'Generic - Sensex, Nifty, Dynamic Copies, Performance, BFSI\nCreative - 2 copies, 1 cta\nTechnical - 1 LP, Single LP\nAnimation -Fade in up\nBrand - Franklin Templeton'),
(40, 'Display', 'Rich Media', 'Dating', 'Pending', '300x250, 300x600, 320x480, 480x320', '8 min', 'Auto', '', 'Help HC with the master look of your Creative and your Programmatic creatives will be ready within hours!\n\nRequirements:\nOpen Files in .psd or .ai format\nVideo under 30s\n\n', 'https://ad.hockeycurve.com/ad.php?zoneid=300x600&client=shaadiauto&fcat=auto1set', 'Generic - Dating, Shaadi, Marriage, Vernacular, Branding, Performance\nCreative - 1 copy, 1 cta\nTechnical - 1 LP, Single LP\nAnimation -Zoom, popup\nBrand - Shaadi'),
(41, 'Video', 'In Banner Video', 'Dating', 'Pending', '300x600, 320x480, 480x320, 970x250', '8 min', 'Auto', '', 'Help HC with the master look of your Creative with the applicable video and your Programmatic creatives will be ready within hours!\n\nAds are for everyone! A layer of vernacular language creates a personalized experience for your regional audience!\n\nRequirements:\nOpen Files in .psd or .ai format\nVideo under 30s\n\n', 'https://ad.hockeycurve.com/ad.php?zoneid=300x600&client=shaadivideo&fcat=shv1d', 'Generic - Dating, Shaadi, Marriage, Vernacular,  Branding, Performance, Video\nCreative - 1 copy, 1 cta\nTechnical - 1 LP, Single LP, App store, Play store\nBrand - Shaadi'),
(42, 'Display', 'Auto Carousel - feed based', 'Valentines', '', '300x600, 320x480, 480x320, 970x250', '8 min', 'Auto', '', 'Help HC with the master creative and we will turn into a carousel instantly!\n\nFeed intergration helps you to display permutations and combinations of products for your ongoing sale.\n\nRequirements:\nOpen Files in .psd or .ai format\nProduct Feed/ Product Images\n\n', 'https://ad.hockeycurve.com/ad.php?zoneid=300x250&client=mands&fcat=ffa20', 'Generic - Apparel, Bras, Lingerie, Carousel, Feed, Performance, Auto, Sale, \nCreative - 2 copies, 1 cta\nTechnical - 1 LP, Single LP, App store, Play store\nAnimation -Fade in up, auto \nBrand - Marks & Spencer, MnS, M&S'),
(43, 'Display', 'Swipe Carousel + Countdown - feed based', 'Valentines', '', '300x600, 320x480, 480x320, 970x250', '10 min', 'Auto + Manual', '', 'Create the urgency in the user\'s mind by adding a countdown in your ad!\n\nNot just that, add a deck of product for the user to choose from, better yet display it in an innovative format that will help increase your engagement numbers!\n\nNudge added to card promts the user to swipe!\n\nRequirements:\r\nOpen Files in .psd or .ai format\r\nProduct Feed/ Product Images\nCountdown start and end date', 'https://ad.hockeycurve.com/ad.php?zoneid=300x250&client=mands&fcat=off20', 'Generic - Apparel, Bras, Lingerie, Carousel, Feed, Sale, Performance,Swipe,  Countdown\nCreative - 2 copies, 1 cta\nTechnical - 1 LP, Single LP, App store, Play store\nAnimation -Fade in up, auto ,Nudge, Swipe\nBrand - Marks & Spencer, MnS, M&S'),
(44, 'Display', 'In Banner Search Bar - Recommendation based', 'Valentines', '', '300x600, 320x480, 480x320, 970x250', '15 min', 'Manual', '', 'Description:\nLooking for an answer? Google it\nLooking for a product, search in ad directly!\n\nThis format hints at what you should be typing in the search bar to get the most relevant product.\n\nRequirements:\nOpen File in .psd or .ai format\nList of product recommendations', 'https://ad.hockeycurve.com/ad.php?zoneid=300x600&client=mands&fcat=srchani', 'Generic - Apparel, Bras, Lingerie, Sleepwear, knickers, Carousel, Feed, Performance,Swipe, Nudge, Sale, Recommendation\nCreative - 2 copies, 1 cta\nTechnical - 1 LP, Single LP, App store, Play store\nAnimation -Fade in up, auto ,Nudge, Swipe\nBrand - Marks & Spencer, MnS, M&S'),
(45, 'Display', 'Circle carousel - Non feed', 'Valentines', '', '300x600, 320x480, 480x320, 970x250', '10 min', 'Auto', '', 'Description:\nYet another interesting way to catch your users attention and showcase all your products!\n\nThis carousel shape occupies relatively less area in your canvas, allowing you to add multiple elements in your ad!\n\nRequirements:\nOpen File in .psd or .ai format\nProduct Feed/ Product Images', 'https://ad.hockeycurve.com/ad.php?zoneid=300x600&client=mands&fcat=8dc8', 'Generic - Apparel, Bras, Lingerie, Sleepwear, knickers, casual wear, circle, Carousel, Feed, Performance,Sale\nCreative - 2 copies, 1 cta\nTechnical - 1 LP, Single LP, App store, Play store\nAnimation -Fade in up, auto ,Nudge, Swipe\nBrand - Marks & Spencer, MnS, M&S'),
(46, 'Display', 'Tap To Reveal', 'Valentines', '', '300x600, 320x480, 480x320, 970x250', '10 min', 'Manual', '', 'Description:\nHave an exclusive product range to display?\n\nCreate curiosity among your users using this interesting format! It allows you to create the big reveal and increase engagement on the ad!\n\nRequirements:\nOpen File in .psd or .ai format\nProduct Images', 'https://ad.hockeycurve.com/ad.php?zoneid=300x600&client=mands&fcat=dupl3', 'Generic - Apparel, Bras, Lingerie, Carousel, Feed, Performance, Tap, color reveal, Interactive, colour reveal\nCreative - 2 copies, 1 cta, gesture\nTechnical - 1 LP, Single LP, App store, Play store\nAnimation -Fade in up, auto ,Nudge, Swipe\nBrand - Marks & Spencer, MnS, M&S'),
(47, 'Display', 'Countdown Creative - text based', 'Valentines', '', '300x600, 320x480, 480x320, 970x250', '10 min', 'Auto', '', 'Description:\nThis template is especially best suited for your sales that will be lasting for an n number of days.\n\nShowcase your products alongside to build relevance and pursuade the user to make a purchase.\n\nRequirements:\r\nOpen File in .psd or .ai format\r\nProduct Images', 'https://ad.hockeycurve.com/ad.php?zoneid=300x600&client=marktday&fcat=2vc7pt', 'Generic -Apparel, Bras, Lingerie, Sleepwear, Carousel, Feed, Performance,countdown, text countdown, Sale\nCreative - 2 copies, 1 cta, Countdown panel, copy based\nTechnical - 1 LP, Single LP, App store, Play store\nAnimation -Fade in up, auto \nBrand - Marks & Spencer, MnS, M&S'),
(48, 'Display', 'Countdown Creative - numeric based', 'Valentines', '', '300x600, 320x480, 480x320, 970x250', '8 min', 'Auto', '', 'Description:\r\nWhat better way to excite consumer than a countdown? Create that feeling of thrill, excitement and suspense with an automated countdown powered by HC.\r\n\r\n\r\nRequirements:\r\nOpen Files s in .psd or .ai format\r\nStarting and End date of the sale\r\n', 'https://ad.hockeycurve.com/ad.php?zoneid=300x600&client=marktday&fcat=tire13', 'Generic -Apparel, Bras, Lingerie, Sleepwear, Carousel, Feed, Performance,countdown, numeric countdown, Sale\nCreative - 2 copies, 1 cta, Countdown panel, copy based\nTechnical - 1 LP, Single LP, App store, Play store\nAnimation -Fade in up, auto \nBrand - Marks & Spencer, MnS, M&S'),
(49, 'Display', 'In Banner Dropdown - Store locator', 'Valentines', '', '300x600, 320x480, 480x320, 970x250', '15 min', 'Manual', '', '\nDescription:\r\nThis format picks up your geo location automatically with the help of API and showcases stores in your city to provide an end to end experience.\r\n\r\nThis will then redirect to your desired landing page\r\n\r\nRequirements:\r\nOpen Files in .psd or .ai format\r\nList of cities and stores (Here)\r\n', 'https://ad.hockeycurve.com/ad.php?zoneid=300x600&client=mands&fcat=mscity', 'Generic -Apparel, Bras, Lingerie, Sleepwear, Carousel, Feed, Performance,stores, store locator, dropdown, Sale, Geo Location\nCreative - 2 copies, 1 cta, dropdown panel\nTechnical - 1 LP, Single LP\nAnimation -Fade in up, auto \nBrand - Marks & Spencer, MnS, M&S'),
(50, 'Display', '360 Product Carousel - feed based', 'Valentines', '', '300x600, 320x480, 480x320, 970x250', '15 min', 'Auto', '', 'Description:\r\nTalk about innovation and you have it!\r\n\r\nThis ad format allows a unique experience to showcase your ad elements. The products rotate and emphasize only on 1 product at a time by zooming in ensuring that  the user has had a look at all of them.\r\n\r\nRequirements:\r\nOpen Files s in .psd or .ai format\r', 'https://ad.hockeycurve.com/ad.php?zoneid=300x600&client=mands&fcat=dc2', 'Generic -Apparel, Bras, Lingerie, Sleepwear, Carousel, Feed, Performance, Sale, 360 \nCreative - 2 copies, 1 cta, dropdown panel\nTechnical - 1 LP, Single LP\nAnimation -Fade in up, auto \nBrand - Marks & Spencer, MnS, M&S'),
(51, 'Display', 'Cube carousel - feed based', 'Valentines', '', '300x600, 320x480, 480x320, 970x250', '10 min', 'Auto', '', 'Description:\r\nThis is one of the newest formats launches at HC!\r\nThis format is an attention grabber with its animation and allows us to showcase 6 products on all sides of the cube.\r\n\r\nRequirements:\r\nOpen Files in .psd or .ai format\r\nHigh Resolution Images of the product\r', 'https://ad.hockeycurve.com/ad.php?zoneid=300x600&client=mands&fcat=dupl2', 'Generic -Apparel, Bras, Lingerie, Sleepwear, Carousel, Feed, Performance, Sale, cube\nCreative - 2 copies, 1 cta, dropdown panel\nTechnical - 1 LP, Single LP\nAnimation -Fade in up, auto \nBrand - Marks & Spencer, MnS, M&S'),
(52, 'Display', 'Swipe + Countdown Creative - Feed based', 'Valentines', '', '300x600, 320x480, 480x320, 970x250, 300x250', '10 min', 'Auto + Manual', '', 'Description:\nThis is a concatenation of two templates, swipe and countdown! It helps create a connect between the product and the sale and encourages the user to make a purchase.\n\nRequirements:\nOpen Files in .psd or .ai format\nHigh Resolution Images of the product\n', 'https://ad.hockeycurve.com/ad.php?zoneid=320x100&client=mands&fcat=off20', 'Generic -Apparel, Bras, Lingerie, Sleepwear, Carousel, Feed, Performance,countdown, numeric countdown, Swipe, nudge, Sale\nCreative - 2 copies, 1 cta, countdown panel\nTechnical - 1 LP, Single LP, App store, Play store\nAnimation -Fade in up, swipe, nudge\nBrand - Marks & Spencer, MnS, M&S'),
(53, 'Display', 'Rich Media Creative with animation - Creative change on every refresh', 'Education', '', '300x600, 320x480, 480x320, 970x250, 300x250', '8 min', 'Auto', '', 'Description:\nDisplay a new ad to your users in every refresh! This ad auto displays various KVs and communication on each refresh at random.\n\nIt is also displays the number instantly post user click allowing instant gratification.\n\nRequirements:\nOpen Files in .psd or .ai format\nContact Information', 'https://ad.hockeycurve.com/ad.php?zoneid=special&client=applyboard&fcat=promo1spl&staging=only', 'Generic -Degree, Admissions, Click to call, Call Now, Performance, Degree\nCreative - 2 copies, 1 cta, Call Now Cta\nTechnical - 1 LP, Single LP, \nAnimation -Fade in up,\nBrand - Applyboard, Yorkville,'),
(54, 'Display', 'Click based carousel', 'Education', '', '300x600, 320x480, 480x320, 970x250, 300x250', '12 min', 'Auto + manual', '', 'Description:\nDisplay a new ad to your users in every refresh! This ad auto displays various KVs and communication on each refresh at random.\n\nIt is also displays the number instantly post user click allowing instant gratification.\n\nRequirements:\nOpen Files in .psd or .ai format\nContact Information', 'https://ad.hockeycurve.com/ad.php?zoneid=special&client=cuemath&fcat=classspecial&staging=only', 'Generic -Click, USPs, Features, Carousel, Auto, Performance\nCreative - 2 copies, 1 cta, 3 USPs, KVs\nTechnical - 1 LP, Single LP,\nAnimation -Fade in up, Shimmer\nBrand - Cuemath'),
(55, 'Video', 'In Banner Video Creatives', 'Education', '', '300x600, 320x480, 480x320, 970x250, 300x250', '8 min', 'Auto', '', 'Description:\r\nHelp HC with the master look of your Creative with the applicable video and your Programmatic creatives will be ready within hours!\r\n\r\nRequirements:\r\nOpen Files in .psd or .ai format\r\nVideo under 30s\r\n', 'https://ad.hockeycurve.com/ad.php?zoneid=300x250&client=extramarks&fcat=parentios', 'Generic - Video, Branding, Performance, USPs, Features, Video,\nCreative - 2 copies, 1 cta, 4 USPs, KV, Download App Cta\nTechnical - 1 LP, Single LP,\nAnimation -Fade in up, Zoom\nBrand - Extra Marks'),
(56, 'Display', 'In Banner Dropdown Creative', 'Education', '', '300x600, 320x480, 480x320, 970x250, 300x250', '15 min', 'Manual', '', 'Description:\nSelect the subject and the date from the dropdown to find out how to master it!\n\nDropdown helps increase user engagement and interactivity.\n\nRequirements:\nOpen Files in .psd or .ai format\nVideo under 30s\n', 'https://ad.hockeycurve.com/ad.php?zoneid=special&client=tatastudi&fcat=studispl&staging=only', 'Generic - Video, Branding, Performance, USPs, Features, Video, Dropdowns, double dropdown\nCreative - 2 copies, 1 cta, \nTechnical - 1 LP, Single LP,\nAnimation -Fade in up, Zoom\nBrand - Extra Marks'),
(57, 'Display', 'Study Time Calculator', 'Education', '', '', '15 min', 'Manual', '', '', 'https://ad.hockeycurve.com/ad.php?zoneid=special&client=tatastudi&fcat=examspl&staging=only', 'Generic - Dropdown, Subject, Grade, Interactive, Performance,dynamic calculator, Study time calculator, Study Planner\nCreative - 2 copies, 3 ctas, 2 frame banner\nTechnical - 1 LP, Single LP,\nAnimation -Shimmer\nBrand - Tata Studi'),
(58, 'Display', 'Click based carousel - Desktop', 'Education', '', '', '12 min', 'Auto + manual', '', '', 'https://ad.hockeycurve.com/ad.php?zoneid=special&client=vedantu&fcat=desktopsp&staging=only', 'Click, USPs, Features, Carousel, Auto, Performance'),
(59, 'Display', 'Auto Carousel', 'Education', '', '', '10  min', 'Auto + manual', '', '', 'https://ad.hockeycurve.com/ad.php?zoneid=300x250&client=whitehatjr&fcat=demo1', 'Carousel, Auto, Testimonials, Performance, Branding'),
(60, 'Display', 'Vertical Slider', 'Education', '', '', '8 min', 'Auto + manual', '', '', 'https://ad.hockeycurve.com/ad.php?zoneid=300x250&client=whitehatjr&fcat=demo4', 'Intercative, Slider, Performance'),
(61, 'Display', 'Custom rich media creative with animation', 'Education', '', '', '12 min', 'Auto + manual', '', '', 'https://ad.hockeycurve.com/ad.php?zoneid=300x600&client=byjus&fcat=spinwheel', 'Interactive, Motion Graphic, Animation, branding'),
(62, 'Display', 'Custom rich media creative with animation', 'Education', '', '', '12 min', 'Auto + manual', '', '', 'https://ad.hockeycurve.com/ad.php?zoneid=980x40&client=voot&partner=dbm&fcat=bb12', 'Interactive, Motion Graphic, Animation, branding'),
(63, 'Display', 'Video Expando', 'OTT', '', '', '10 min', 'Auto + manual', '', '', 'https://ad.hockeycurve.com/ad.php?zoneid=1290x250&client=htimes&fcat=viacom5&staging=only', 'Expando, Video, Branding, Performance, Combination, movie release'),
(64, 'Display', 'Video Expando', 'OTT', '', '', '12 min', 'Auto + manual', '', '', 'https://ad.hockeycurve.com/ad.php?zoneid=300x250&amp;client=amazonp&amp;fcat=newinjs', 'Expando, Video, Branding, Performance, Combination, movie release'),
(65, 'Display', 'Cinemahraph + video', 'OTT', '', '', '10 min', 'Auto + manual', '', '', 'https://ad.hockeycurve.com/ad.php?zoneid=special&client=amazonp&fcat=interactspl&staging=only', 'Cinemagraph, Movie release, motion bg, video, combination, branding , performance'),
(66, 'Display', 'Genre based Interactive dropdown', 'OTT', '', '', '15 min', 'Manual', '', '', 'https://ad.hockeycurve.com/ad.php?zoneid=300x250&client=amazons&fcat=highlight', 'Dropdown, Genre, intercation, carousel, auto, recommendation, Combination, Performance '),
(67, 'Display', 'Moment Marketing - Copy console', 'OTT', '', '', '20 min', 'Manual', '', '', '', 'Moment marketing, dynamic copies, console, customization, sports, Performance, cricket'),
(68, 'Display', 'Moment Marketing - Events', 'OTT', '', '', '20 min', 'Auto', '', '', 'https://ad.hockeycurve.com/ad.php?zoneid=300x250&client=aha&fcat=tamilv2', 'Moment marketing, cricket, moments, key events, highlights, pre-match, post-match, ODI, T20I sports, performance, '),
(69, 'Display', 'Auto carousel - Non Feed', 'OTT', '', '', '10 min', 'Auto', '', '', 'https://ad.hockeycurve.com/ad.php?zoneid=300x600&client=aha&fcat=comedy', 'Carousel, auto, performance, movies'),
(70, 'Display', 'Genre Based Auto Carousel', 'OTT', '', '', '12 min', 'Auto', '', '', 'https://ad.hockeycurve.com/ad.php?zoneid=special&client=amazonp&fcat=actionspl&staging=only', 'Carousel, auto, performance, movies, recommendation, genre'),
(71, 'Display', 'Genre Based Auto Carousel - 2 cards', 'OTT', '', '', '12 min', 'Auto', '', '', 'https://ad.hockeycurve.com/ad.php?zoneid=special&client=discoveryp&fcat=armysnspecial&staging=only', 'Carousel, auto, performance, movies, recommendation, genre'),
(72, 'Display', 'Auto carousel - Non Feed', 'OTT', '', '', '10 min', 'Auto', '', '', 'https://ad.hockeycurve.com/ad.php?zoneid=300x600&client=aprimeauto&fcat=edbmhero', 'Carousel, auto, performance, movies, recommendation, category'),
(73, 'Display', 'Add To calendar', 'OTT', '', '', '15 min', 'Auto', '', '', 'https://ad.hockeycurve.com/ad.php?zoneid=300x250&client=nbc&fcat=skysa&staging=only', 'Add to calender, date, branding, performance, movie release'),
(74, 'Display', 'Rich Media creative with animation', 'OTT', '', '', '8 min', 'Auto', '', '', 'https://ad.hockeycurve.com/ad.php?zoneid=300x600&client=aprimeauto&fcat=ama1dao', 'date, branding, performance, movie release'),
(75, 'Display', 'Mashup auto carousel', 'OTT', '', '', '12 min', 'Auto', '', '', 'https://ad.hockeycurve.com/ad.php?zoneid=300x250&client=twitter&fcat=thalaivi', 'Mashup, carousel, auto, branding, tranding movies , performance'),
(76, 'Display', 'Countdown Creative - Numeric', 'OTT', '', '', '10 min', 'Auto', '', '', 'https://ad.hockeycurve.com/ad.php?zoneid=300x600&client=aprimeauto&fcat=lapvter', 'Countdown, Numeric countdown, Performance, Branding, Movie release'),
(77, 'Display', 'Countdown Creative - Text Based', 'OTT', '', '', '8 min', 'Auto', '', '', 'https://ad.hockeycurve.com/ad.php?zoneid=300x250&client=aprime&fcat=apvcampg', 'Countdown, text countdown, movie release, branding, performance'),
(78, 'Display', 'Dynamic Geo + copy ', 'OTT', '', '', '12 min', 'Auto', '', '', 'https://ad.hockeycurve.com/ad.php?zoneid=300x250&client=amazonp&fcat=farziapv', 'Geo Location, vernacular, Hinglish, Branding, Performance'),
(79, 'Display', 'Cinemagraph', 'OTT', '', '', '12 min', 'Auto', '', '', 'https://ad.hockeycurve.com/ad.php?zoneid=300x600&client=discauto&fcat=div1s1', 'Cinemagraph, Movie release, motion bg, branding , performance'),
(80, 'Display', 'In Banner Video Ad', 'OTT', '', '', '10 min', 'Auto', '', '', 'http://ad.hockeycurve.com/ad.php?zoneid=970x250&client=zeetalkies&fcat=all', 'Show release, video, branding, performance'),
(81, 'Display', 'Video  Ad + Set Reminder', 'OTT', '', '', '10 min', 'Auto', '', '', 'http://ad.hockeycurve.com/ad.php?zoneid=970x250&client=zeetalkies&fcat=all', 'Video, Set reminder, event reminder, branding, performance, combination'),
(82, 'Display', 'Vertical Slider', 'Food', '', '', '12 min', '', '', '', 'https://ad.hockeycurve.com/ad.php?zoneid=300x250&client=swiggy&fcat=swigy2', 'Interaction, food, slider, performance'),
(83, 'Display', 'Auto Carousel - Non feed', 'Food', '', '', '12 min', '', '', '', 'https://ad.hockeycurve.com/ad.php?zoneid=300x250&client=swiggy&fcat=swigydpa1', 'Food, cuisine, meal, meal time, carousel, auto, feed, performance'),
(84, 'Display', 'Auto Carousel - feed', 'Food', '', '', '10 min', '', '', '', 'https://ad.hockeycurve.com/ad.php?zoneid=300x250&client=swiggy&fcat=swigydpa2', 'Food, auto, carousel, feed, performance'),
(85, 'Display', 'Auto carousel + Dynamic Time of the day', 'Food', '', '', '15 min', '', '', '', 'https://ad.hockeycurve.com/ad.php?zoneid=300x250&client=swiggy&fcat=swigy6', 'Food, dynamic tiem, dynamic copies, auto, carousel'),
(86, 'Display', 'Vernacular Rich media creative with animation + Dynamic Copy and bg', 'Food', '', '', '12 min', '', '', '', 'https://ad.hockeycurve.com/ad.php?zoneid=300x250&client=swiggy&fcat=swiggy3', 'Food, Dynamic bg, dynamic copies, performance'),
(87, 'Display', 'Search', 'Food', '', '', '13 min', '', '', '', 'https://ad.hockeycurve.com/ad.php?zoneid=300x250&client=swiggy&fcat=swigy11', 'Food, search, intercative, performance'),
(88, 'Display', 'Auto Swipe - Dynamic Time + Weather+ Feed', 'Food', '', '', '17 min', '', '', '', 'https://ad.hockeycurve.com/ad.php?zoneid=300x250&client=swiggy&fcat=swigy8', 'Food, dynamic time, dynamic weather, auto, carousel, dynamic product, performance'),
(89, 'Display', 'Auto Swipe - Dynamic Time + Feed', 'Food', '', '', '15 min', '', '', '', 'https://ad.hockeycurve.com/ad.php?zoneid=300x250&client=swiggy&fcat=swigy9', 'Food, dynamic time, auto, carousel, dynamic product, swipe, performance'),
(90, 'Display', 'Dropdown', 'Food', '', '', '12 min', '', '', '', 'https://ad.hockeycurve.com/ad.php?zoneid=300x250&client=swiggy&fcat=swigy10', 'Food, dynamic time, dropdown, interaction, performance'),
(91, 'Display', 'Canvas Scratch To reveal', 'Food', '', '', '12 min', '', '', '', 'https://ad.hockeycurve.com/ad.php?zoneid=300x250&client=swiggy&fcat=swigy12', 'Food, scratch, Interactive, '),
(92, 'Display', 'Rich Media creative with Animation', 'Food', '', '', '15 min', '', '', '', 'https://ad.hockeycurve.com/ad.php?zoneid=300x250&client=swiggyinsta&fcat=swigydc1', ''),
(93, 'Display', 'Dropdown', 'Food', '', '', '11 min', '', '', '', 'https://ad.hockeycurve.com/ad.php?zoneid=300x250&client=swiggyinsta&fcat=swigydc4', ''),
(94, 'Display', 'Tap to reveal + Dynamic Date', 'Food', '', '', '10 min', '', '', '', 'https://ad.hockeycurve.com/ad.php?zoneid=300x250&client=swiggyinsta&fcat=swigydc6', ''),
(95, 'Display', 'In Banner Video', 'Food', '', '', '8 min', '', '', '', 'https://ad.hockeycurve.com/ad.php?zoneid=300x600&client=swiggyinstavideo&fcat=instswig', ''),
(96, 'Display', 'Dynamic Geo + offer', 'Food', '', '', '12 min', '', '', '', 'https://ad.hockeycurve.com/ad.php?zoneid=300x600&client=swiggy&fcat=swigmck1', ''),
(97, 'Display', 'Countdown Timer', 'Food', '', '', '15 min', '', '', '', 'https://ad.hockeycurve.com/ad.php?zoneid=300x600&client=licioustimer&fcat=fnjd57', ''),
(98, 'Display', 'Cube Creative - Feed based + Dynamic City', 'Food', '', '', '10 min', '', '', '', 'https://ad.hockeycurve.com/ad.php?zoneid=300x600&client=licious&fcat=zhh833', ''),
(99, 'Display', 'Dropdown', 'Food', '', '', '15 min', '', '', '', 'https://ad.hockeycurve.com/ad.php?zoneid=300x250&client=licious&fcat=lic23', ''),
(100, 'Display', 'Search - Recommendation based + Dynamic Cit', 'Food', '', '', '17 min', '', '', '', 'https://ad.hockeycurve.com/ad.php?zoneid=300x600&client=licholi&fcat=licdc4&geo=true', ''),
(101, 'Display', '360 Product Carousel - Feed Based + Dynamic City\n', 'Food', '', '', '12 min', '', '', '', 'https://ad.hockeycurve.com/ad.php?zoneid=300x600&client=licious&fcat=b70h0f', ''),
(102, 'Display', 'Interactive Gamified Banner\n', 'Food', '', '', '15 min', '', '', '', 'https://ad.hockeycurve.com/ad.php?zoneid=300x600&client=licholi&fcat=newlic1&geo=true', '');
INSERT INTO `present` (`id`, `ad_format`, `template`, `category`, `average_ctr`, `dimensions`, `duration`, `functionality`, `reviews`, `description`, `demo_link`, `meta_keywords`) VALUES
(103, 'Display', 'Interactive Gamified Banner\n', 'Food', '', '', '10 min', '', '', '', 'https://ad.hockeycurve.com/ad.php?zoneid=300x250&client=licious&fcat=liciousdc7&geo=true', ''),
(104, 'Display', 'Spin The Wheel', 'Food', '', '', '12 min', '', '', '', 'https://ad.hockeycurve.com/ad.php?zoneid=300x250&client=licious&fcat=mhqf60', '');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `present`
--
ALTER TABLE `present`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `present`
--
ALTER TABLE `present`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=105;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
